services:
  fellsidedigital:
    container_name: fellside_digital
    image: ${DOCKER_REGISTRY-}fellsidedigital
    build:
      context: .
      dockerfile: FellsideDigital/Dockerfile
    environment:
      # Application Settings
      - ConnectionStrings__DefaultConnection=Host=fellside_digital_postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - Email__Username=${EMAIL__USERNAME}
      - Email__Password=${EMAIL__PASSWORD}
      - Email__FromAddress=${EMAIL__FROMADDRESS}
      - Email__TenantId=${TENANT_ID}
      - Email__ClientId=${CLIENT_ID}
      - Email__ClientSecret=${CLIENT_SECRET}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      fellside_digital_postgres:
        condition: service_healthy
    volumes:
      - keys_volume:/app/keys

  fellside_digital_postgres:
    image: postgres:15
    container_name: fellside_digital_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  keys_volume:
