services:
  fellsidedigital:
    image: ${DOCKER_REGISTRY-}fellsidedigital
    build:
      context: .
      dockerfile: FellsideDigital/Dockerfile
    environment:
      # Application Settings - in prod, DATABASE_URL comes from Railway or external service
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - Email__Username=${EMAIL__USERNAME}
      - Email__Password=${EMAIL__PASSWORD}
      - Email__FromAddress=${EMAIL__FROMADDRESS}
      - Email__AdminEmail=${EMAIL__ADMINEMAIL}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
      - "8081:8081"
